name: Docker build and publish

on: push

env:
  namespace: healthvue
  deployment: healthvue
  tag: ${{ vars.DOCKERHUB_USERNAME}}/healthvue:${{ github.sha }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: ${{ inputs.dockerpush }}
      #     platforms: linux/amd64,linux/arm64
      #     tags: ${{ vars.DOCKERHUB_USERNAME}}/healthvue:${{ github.sha }}

      - name: Install kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Update image
        run: kubectl set image deployment/${{ env.deployment }} ${{ env.deployment }}=${{ env.tag }} -n ${{ env.namespace }}
